steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build Image
  entrypoint: bash
  args:
    - -c
    - |
      docker build . -t us-east1-docker.pkg.dev/$PROJECT_ID/app/sdr-agent:latest \
      && docker push us-east1-docker.pkg.dev/$PROJECT_ID/app/sdr-agent:latest 

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  id: Deploy API
  args: ['run', 'deploy', sdr-agent,
             --image=us-east1-docker.pkg.dev/$PROJECT_ID/app/sdr-agent:latest,
             '--region=us-east1', '--service-account=vertex-ai-consumer@$PROJECT_ID.iam.gserviceaccount.com',
              '--allow-unauthenticated',
              '--set-env-vars=STREAMLIT_SERVER_PORT=8080',
              '--set-secrets=PROXYCURL_API_KEY=PROXYCURL_API_KEY:latest, SERPAPI_API_KEY=SERPAPI_API_KEY:latest']
  waitFor: [ 'Build Image' ]

images:
- 'us-east1-docker.pkg.dev/$PROJECT_ID/app/sdr-agent:latest'